module.exports = {
	// counter
	ADD: 'ADD',

  GET_TRIP_REQUEST: "GET_TRIP_REQUEST",
  GET_TRIP_SUCCESS: "GET_TRIP_SUCCESS",
  GET_TRIP_FAILURE: "GET_TRIP_FAILURE",

	GET_AGENT_REQUEST: "GET_AGENT_REQUEST",
	GET_AGENT_SUCCESS: "GET_AGENT_SUCCESS",
	GET_AGENT_FAILURE: "GET_AGENT_FAILURE",

	GET_PLACEDETAIL_REQUEST: "GET_PLACEDETAIL_REQUEST",
	GET_PLACEDETAIL_SUCCESS: "GET_PLACEDETAIL_SUCCESS",
	GET_PLACEDETAIL_FAILURE: "GET_PLACEDETAIL_FAILURE",

	UPDATE_DATE: "UPDATE_DATE",
	UPDATE_DESTINATION: "UPDATE_DESTINATION",
	UPDATE_FORM: "UPDATE_FORM",
}
